version: "3.9"

networks:
  ms-network:
    driver: bridge

services:
  eureka:
    build: ./discovery-server
    environment:
      - "JAVA_OPTS=-Dinstance.prefer-ip-address=false -Deureka.eureka.instance.hostname=eureka-server -Deureka.client.serviceUrl.defaultZone=http://eureka-server:8761/eureka"
    ports:
      - "8761:8761"
    networks:
      - ms-network
    hostname: eureka

  api-gateway:
    build: ./api-gateway
    environment:
      - "JAVA_OPTS=-Deureka.client.serviceUrl.defaultZone=http://eureka-server:8761/eureka"
    depends_on:
      - eureka
    ports:
      - "8082:8082"
    networks:
      - ms-network
    hostname: api-gateway

  produtos-ms-8090:
    build: ./produtos-ms
    environment:
      - "JAVA_OPTS=-Deureka.client.serviceUrl.defaultZone=http://eureka-server:8761/eureka"
      - "SERVER_PORT=8090"
    depends_on:
      - eureka
    ports:
      - "8090:8090"
    networks:
      - ms-network
    hostname: produtos8090

  produtos-ms-8091:
    build: ./produtos-ms
    environment:
      - "JAVA_OPTS=-Deureka.client.serviceUrl.defaultZone=http://eureka-server:8761/eureka"
      - "SERVER_PORT=8091"
    depends_on:
      - eureka
    ports:
      - "8091:8091"
    networks:
      - ms-network
    hostname: produtos8091

  produtos-ms-8092:
    build: ./produtos-ms
    environment:
      - "JAVA_OPTS=-Deureka.client.serviceUrl.defaultZone=http://eureka-server:8761/eureka"
      - "SERVER_PORT=8092"
    depends_on:
      - eureka
    ports:
      - "8092:8092"
    networks:
      - ms-network
    hostname: produtos8092

  axonserver:
    image: axoniq/axonserver
    hostname: axonserver
    volumes:
      - my-axon-server-config:/config:ro
      - my-axon-server-data:/data
      - my-axon-server-events:/eventdata
    ports:
      - '8024:8024'
      - '8124:8124'
    networks:
      - ms-network

volumes:
  my-axon-server-config:
    driver: local
    driver_opts:
      type: none
      device: ./my-axon-server/config
      o: bind

  my-axon-server-data:
    driver: local
    driver_opts:
      type: none
      device: ./my-axon-server/data
      o: bind

  my-axon-server-events:
    driver: local
    driver_opts:
      type: none
      device: ./my-axon-server/events
      o: bind